services:
  auth:
    container_name: "auth"
    image: python-base:1.0.0
    restart: on-failure
    depends_on:
      - auth_db
    working_dir: /opt/app/
    volumes:
      - ./auth/:/opt/app/auth/
      - ./secrets/:/opt/app/secrets/
    ports:
      - "8888:8888"
    networks:
      - auth-auth_db
    env_file:
      - ./envs/auth.env
    command: [ "uvicorn", "auth.main:app", "--host", "0.0.0.0", "--port", "8888", "--reload" ]

  auth_db:
    container_name: "auth_db"
    image: "postgres:14-alpine"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auth-auth_db
    env_file:
      - ./envs/auth.env


networks:
  auth-auth_db:
    driver: bridge

volumes:
  postgres_data:
